### ISSUE TITLE
Data curator gets slower when number of epochs > 500

### ISSUE THREAD

**Issue by ragavsathish** [Schwartz-AlaLaurila-Labs/sa-labs-analysis#4]

**Comment by lucadellasantina** [comment]
This bug lays within the destructor function of the JTreeNode wrapper class "TreeNode", as part of the dependency toolbox JavaTreeWrapper v1.0 

The destruction of children nodes was recursively called before nObj.jNode was freed up, progressively slowing down the destructor as the number of epochs to delete increased. 

Attached is the patched TreeNode.m, it needs to be replaced inside your folder ~/MATLAB/
Toolboxes/JavaTreeWrapper_v1.0/JavaTreeWrapper/+uiextras/jTree/

[TreeNode.zip](https://github.com/Schwartz-AlaLaurila-Labs/sa-labs-analysis/files/1773259/TreeNode.zip)

**Comment by ragavsathish** [comment]
Thank you @lucadellasantina . I merged your pull request and notified the same in ToolboxRegistry. https://github.com/ToolboxHub/ToolboxRegistry/pull/41

**Comment by ragavsathish** [comment]
Registry updated.
