### ISSUE TITLE
Possibility to remove only one channel from epochs in multi-channel recordings

### ISSUE THREAD

**Issue by JohanWesto** [Schwartz-AlaLaurila-Labs/sa-labs-analysis#7]
It would be useful to have the option to only discard the recording from one channel when recording simultaneoulsy from two or more channels. It will be very wasteful to delete a whole epoch if only one out of two, three or four channels are bad. In this case, it would be very handy to have an option to only remove a particular channel instead.

**Comment by ragavsathish** [comment]
![image](https://user-images.githubusercontent.com/7013764/47468192-a3890400-d802-11e8-9b11-19324356ad5f.png)

@JohanWesto Will this work ?

**Comment by JohanWesto** [comment]
Looks good to me
